=== MaksymMoskalenko2005/RepositoryMoskalenkoModul1/PackageLaboratoryWork2/Task1/lab2_1.dtd
<!ELEMENT card (university, info)>
<!ELEMENT info (name, faculty, serial, issued, valid, group, rector)>
<!ELEMENT university (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT faculty (#PCDATA)>
<!ELEMENT serial (#PCDATA)>
<!ELEMENT issued (#PCDATA)>
<!ELEMENT valid (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT rector (#PCDATA)>

=== MaksymMoskalenko2005/RepositoryMoskalenkoModul1/PackageLaboratoryWork2/Task1/lab2_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE card SYSTEM "lab2_1.dtd">
<?xml-stylesheet type="text/css" href="lab2_1.css"?>
<card>
    <university>Київський авіаційний інститут</university>
    <info>
        <name>Москаленко Максим Андрійович</name>
        <faculty>Факультет комп'ютерних наук та технологій</faculty>
        <serial>Серія, номер: КВ12345678</serial>
        <issued>Виданий: 01.09.2022</issued>
        <valid>Дійсний до: 31.08.2026</valid>
        <group>Група: Б-121-22-1-ПІ</group>
        <rector>Ректор: Ксенія Семенова</rector>

    </info>
</card>
